// <auto-generated />
using System;
using Data.ArmsContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ArmsDbContext))]
    [Migration("20240917183641_MGDataMajor")]
    partial class MGDataMajor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("SPId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAccountActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8c777a9-55b9-4b3d-860a-d7b56e4c24b7"),
                            AccessFailedCount = 0,
                            CampusId = "Hanoi",
                            ConcurrencyStamp = "aa9a6b06-1756-4e85-bf18-536580558f50",
                            Email = "AdminHaNoi@gmail.com",
                            EmailConfirmed = true,
                            Fullname = "Admin Hanoi",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINHANOI@GMAIL.COM",
                            NormalizedUserName = "ADMINISTRATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEHPXWoKitclqpwtmL6BPfULJvWxwd6VtxPLN4nL1yk4C7hSjJI+hp7x054qfmyIQ4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37454b97-331a-4332-af72-854ee61947d8",
                            TwoFactorEnabled = false,
                            UserName = "Administrator",
                            isAccountActive = false
                        });
                });

            modelBuilder.Entity("Data.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampusId");

                    b.ToTable("Campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "Hanoi",
                            Address = "Cổng số 1, Tòa nhà FPT Polytechnic, 13 phố Trịnh Văn Bô, phường Phương Canh, quận Nam Từ Liêm, TP Hà NộiKm12 Cầu Diễn, Phường Phúc Diễn, Quận Bắc Từ Liêm, Hà Nội",
                            CampusName = "Hà Nội",
                            PhoneNumber = "02485820808"
                        },
                        new
                        {
                            CampusId = "Danang",
                            Address = "219 Nguyễn Sinh Sắc, phường Hoà Minh, quận Liên Chiểu, TP Đà Nẵng",
                            CampusName = "Đà Nẵng",
                            PhoneNumber = "02363710999"
                        },
                        new
                        {
                            CampusId = "Cantho",
                            Address = "Toà nhà FPT Polytechnic, đường số 22, phường Thường Thạnh,quận Cái Răng, TP Cần Thơ",
                            CampusName = "Cần Thơ",
                            PhoneNumber = "0983881100"
                        },
                        new
                        {
                            CampusId = "HCM",
                            Address = "Tòa nhà QTSC9 (toà T), đường Tô Ký, phường Tân Chánh Hiệp, quận 12, TP HCM.778/B1 Nguyễn Kiệm, phường 04, quận Phú Nhuận, TP HCM",
                            CampusName = "Tp HCM",
                            PhoneNumber = "02866866486"
                        },
                        new
                        {
                            CampusId = "Thanhhoa",
                            Address = "Tòa Beta, Tổ hợp giáo dục FPT, Đại lộ Võ Nguyên Giáp, phường Quảng Thành, TP Thanh Hóa",
                            CampusName = "Thanh Hoá",
                            PhoneNumber = "0913785213"
                        });
                });

            modelBuilder.Entity("Data.Models.Major", b =>
                {
                    b.Property<string>("MajorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MajorID");

                    b.HasIndex("CampusId");

                    b.ToTable("Major", (string)null);

                    b.HasData(
                        new
                        {
                            MajorID = "E",
                            CampusId = "Hanoi",
                            MajorName = "Công nghệ thông tin"
                        },
                        new
                        {
                            MajorID = "A",
                            CampusId = "Hanoi",
                            MajorName = "Ngôn ngữ"
                        },
                        new
                        {
                            MajorID = "S",
                            CampusId = "Hanoi",
                            MajorName = "Quản trị kinh doanh"
                        },
                        new
                        {
                            MajorID = "B",
                            CampusId = "Hanoi",
                            MajorName = "Làm đẹp"
                        },
                        new
                        {
                            MajorID = "O",
                            CampusId = "Hanoi",
                            MajorName = "Ngành khác"
                        });
                });

            modelBuilder.Entity("Data.Models.SpecializeMajor", b =>
                {
                    b.Property<string>("SpecializeMajorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MajorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpecializeMajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializeMajorID");

                    b.HasIndex("MajorID");

                    b.ToTable("SpecializeMajor", (string)null);

                    b.HasData(
                        new
                        {
                            SpecializeMajorID = "ME",
                            MajorID = "E",
                            SpecializeMajorName = "Lập trình mobile"
                        },
                        new
                        {
                            SpecializeMajorID = "GE",
                            MajorID = "E",
                            SpecializeMajorName = "Lập trình game"
                        },
                        new
                        {
                            SpecializeMajorID = "WE",
                            MajorID = "E",
                            SpecializeMajorName = "Lập trình web"
                        },
                        new
                        {
                            SpecializeMajorID = "TE",
                            MajorID = "E",
                            SpecializeMajorName = "Kiểm thử"
                        },
                        new
                        {
                            SpecializeMajorID = "EA",
                            MajorID = "A",
                            SpecializeMajorName = "Ngôn ngữ anh"
                        },
                        new
                        {
                            SpecializeMajorID = "JA",
                            MajorID = "A",
                            SpecializeMajorName = "Ngôn ngữ nhật"
                        },
                        new
                        {
                            SpecializeMajorID = "KA",
                            MajorID = "A",
                            SpecializeMajorName = "Ngôn ngữ hàn"
                        },
                        new
                        {
                            SpecializeMajorID = "SM",
                            MajorID = "S",
                            SpecializeMajorName = "Marketing"
                        },
                        new
                        {
                            SpecializeMajorID = "HM",
                            MajorID = "S",
                            SpecializeMajorName = "Quản trị khách sạn"
                        },
                        new
                        {
                            SpecializeMajorID = "RM",
                            MajorID = "S",
                            SpecializeMajorName = "Quản trị nhà hàng"
                        },
                        new
                        {
                            SpecializeMajorID = "BT",
                            MajorID = "B",
                            SpecializeMajorName = "Phum xăm thẩm mỹ"
                        },
                        new
                        {
                            SpecializeMajorID = "BS",
                            MajorID = "B",
                            SpecializeMajorName = "Chăm sóc da và massage"
                        },
                        new
                        {
                            SpecializeMajorID = "AO",
                            MajorID = "O",
                            SpecializeMajorName = "Kiểm toán"
                        },
                        new
                        {
                            SpecializeMajorID = "SO",
                            MajorID = "O",
                            SpecializeMajorName = "Thư ký văn phòng"
                        },
                        new
                        {
                            SpecializeMajorID = "FO",
                            MajorID = "O",
                            SpecializeMajorName = "Kỹ thuật chế biến món ăn"
                        });
                });

            modelBuilder.Entity("Data.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressRecipientResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CIDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CitizenIentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diploma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiplomaType")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullnameParents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("ImgCitizenIdentification1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgCitizenIdentification2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PermanentAddress")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneParents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RecipientResults")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializeMajor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializeMajor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearOfGraduation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex("CampusId");

                    b.ToTable("StudentProfile", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8fd818f-63f1-49ee-bec5-f7b66cafbfca"),
                            ConcurrencyStamp = "14166a33-0366-42f7-a214-24da50b85dfd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d2d63c5b-d09b-4828-8322-f18ba103fe86"),
                            ConcurrencyStamp = "f06517c9-3902-4e6a-9df5-8aff09b3b79f",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b8c777a9-55b9-4b3d-860a-d7b56e4c24b7"),
                            RoleId = new Guid("b8fd818f-63f1-49ee-bec5-f7b66cafbfca")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.HasOne("Data.Models.Campus", "Campus")
                        .WithMany("Accounts")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Data.Models.Major", b =>
                {
                    b.HasOne("Data.Models.Campus", "Campus")
                        .WithMany("Majors")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Data.Models.SpecializeMajor", b =>
                {
                    b.HasOne("Data.Models.Major", "Major")
                        .WithMany("SpecializeMajors")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Data.Models.StudentProfile", b =>
                {
                    b.HasOne("Data.Models.Account", "Account")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Data.Models.StudentProfile", "AccountId");

                    b.HasOne("Data.Models.Campus", "Campus")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Data.Models.Campus", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Majors");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Data.Models.Major", b =>
                {
                    b.Navigation("SpecializeMajors");
                });
#pragma warning restore 612, 618
        }
    }
}
