// <auto-generated />
using System;
using Data.ArmsContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ArmsDbContext))]
    [Migration("20240917181615_MGMajor")]
    partial class MGMajor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("SPId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAccountActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8c777a9-55b9-4b3d-860a-d7b56e4c24b7"),
                            AccessFailedCount = 0,
                            CampusId = "Hanoi",
                            ConcurrencyStamp = "978d762f-f311-49a7-80a9-a1a9387d640e",
                            Email = "AdminHaNoi@gmail.com",
                            EmailConfirmed = true,
                            Fullname = "Admin Hanoi",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINHANOI@GMAIL.COM",
                            NormalizedUserName = "ADMINISTRATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEO6r3UrMezZSaLX9/xJdiN4GvspweRKH5J1yeQK4bfg4k1TW5naR5vKDVSESitLGUw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ec27679-ce58-4177-aab5-e2630d6d462f",
                            TwoFactorEnabled = false,
                            UserName = "Administrator",
                            isAccountActive = false
                        });
                });

            modelBuilder.Entity("Data.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampusId");

                    b.ToTable("Campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "Hanoi",
                            CampusName = "Hà Nội"
                        },
                        new
                        {
                            CampusId = "Danang",
                            CampusName = "Đà Nẵng"
                        },
                        new
                        {
                            CampusId = "Cantho",
                            CampusName = "Cần Thơ"
                        },
                        new
                        {
                            CampusId = "HCM",
                            CampusName = "Tp HCM"
                        },
                        new
                        {
                            CampusId = "Quynhon",
                            CampusName = "Quy Nhơn"
                        });
                });

            modelBuilder.Entity("Data.Models.Major", b =>
                {
                    b.Property<string>("MajorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MajorID");

                    b.HasIndex("CampusId");

                    b.ToTable("Major", (string)null);

                    b.HasData(
                        new
                        {
                            MajorID = "E",
                            CampusId = "Hanoi",
                            MajorName = "Công nghệ thông tin"
                        },
                        new
                        {
                            MajorID = "A",
                            CampusId = "Hanoi",
                            MajorName = "Ngôn ngữ"
                        },
                        new
                        {
                            MajorID = "S",
                            CampusId = "Hanoi",
                            MajorName = "Quản trị kinh doanh"
                        },
                        new
                        {
                            MajorID = "B",
                            CampusId = "Hanoi",
                            MajorName = "Làm đẹp"
                        },
                        new
                        {
                            MajorID = "O",
                            CampusId = "Hanoi",
                            MajorName = "Ngành khác"
                        });
                });

            modelBuilder.Entity("Data.Models.SpecializeMajor", b =>
                {
                    b.Property<string>("SpecializeMajorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MajorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpecializeMajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializeMajorID");

                    b.HasIndex("MajorID");

                    b.ToTable("SpecializeMajor", (string)null);

                    b.HasData(
                        new
                        {
                            SpecializeMajorID = "ME",
                            MajorID = "E",
                            SpecializeMajorName = "Lập trình mobile"
                        },
                        new
                        {
                            SpecializeMajorID = "GE",
                            MajorID = "E",
                            SpecializeMajorName = "Lập trình game"
                        },
                        new
                        {
                            SpecializeMajorID = "WE",
                            MajorID = "E",
                            SpecializeMajorName = "Lập trình web"
                        },
                        new
                        {
                            SpecializeMajorID = "TE",
                            MajorID = "E",
                            SpecializeMajorName = "Kiểm thử"
                        },
                        new
                        {
                            SpecializeMajorID = "EA",
                            MajorID = "A",
                            SpecializeMajorName = "Ngôn ngữ anh"
                        },
                        new
                        {
                            SpecializeMajorID = "JA",
                            MajorID = "A",
                            SpecializeMajorName = "Ngôn ngữ nhật"
                        },
                        new
                        {
                            SpecializeMajorID = "KA",
                            MajorID = "A",
                            SpecializeMajorName = "Ngôn ngữ hàn"
                        },
                        new
                        {
                            SpecializeMajorID = "SM",
                            MajorID = "S",
                            SpecializeMajorName = "Marketing"
                        },
                        new
                        {
                            SpecializeMajorID = "HM",
                            MajorID = "S",
                            SpecializeMajorName = "Quản trị khách sạn"
                        },
                        new
                        {
                            SpecializeMajorID = "RM",
                            MajorID = "S",
                            SpecializeMajorName = "Quản trị nhà hàng"
                        },
                        new
                        {
                            SpecializeMajorID = "BT",
                            MajorID = "B",
                            SpecializeMajorName = "Phum xăm thẩm mỹ"
                        },
                        new
                        {
                            SpecializeMajorID = "BS",
                            MajorID = "B",
                            SpecializeMajorName = "Chăm sóc da và massage"
                        },
                        new
                        {
                            SpecializeMajorID = "AO",
                            MajorID = "O",
                            SpecializeMajorName = "Kiểm toán"
                        },
                        new
                        {
                            SpecializeMajorID = "SO",
                            MajorID = "O",
                            SpecializeMajorName = "Thư ký văn phòng"
                        },
                        new
                        {
                            SpecializeMajorID = "FO",
                            MajorID = "O",
                            SpecializeMajorName = "Kỹ thuật chế biến món ăn"
                        });
                });

            modelBuilder.Entity("Data.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressRecipientResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CIDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CitizenIentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diploma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiplomaType")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullnameParents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("ImgCitizenIdentification1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgCitizenIdentification2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PermanentAddress")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneParents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RecipientResults")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializeMajor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializeMajor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearOfGraduation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex("CampusId");

                    b.ToTable("StudentProfile", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8fd818f-63f1-49ee-bec5-f7b66cafbfca"),
                            ConcurrencyStamp = "7a05da36-6635-4936-bce2-0a57d7e2b0a8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d2d63c5b-d09b-4828-8322-f18ba103fe86"),
                            ConcurrencyStamp = "2a3bff2b-3c63-498a-8e55-589d6231802a",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b8c777a9-55b9-4b3d-860a-d7b56e4c24b7"),
                            RoleId = new Guid("b8fd818f-63f1-49ee-bec5-f7b66cafbfca")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.HasOne("Data.Models.Campus", "Campus")
                        .WithMany("Accounts")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Data.Models.Major", b =>
                {
                    b.HasOne("Data.Models.Campus", "Campus")
                        .WithMany("Majors")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Data.Models.SpecializeMajor", b =>
                {
                    b.HasOne("Data.Models.Major", "Major")
                        .WithMany("SpecializeMajors")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Data.Models.StudentProfile", b =>
                {
                    b.HasOne("Data.Models.Account", "Account")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Data.Models.StudentProfile", "AccountId");

                    b.HasOne("Data.Models.Campus", "Campus")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Data.Models.Campus", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Majors");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Data.Models.Major", b =>
                {
                    b.Navigation("SpecializeMajors");
                });
#pragma warning restore 612, 618
        }
    }
}
